CREATE TABLE IF NOT EXISTS ai_lab_state (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL UNIQUE,
  generation INT NOT NULL DEFAULT 0,
  iteration_count INT NOT NULL DEFAULT 0,
  capital DECIMAL(18,2) NOT NULL DEFAULT 100000,
  interval_minutes INT NOT NULL DEFAULT 5,
  state_json LONGTEXT NOT NULL,
  last_run_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_lab_iteration (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  generation INT NOT NULL DEFAULT 0,
  champion_json LONGTEXT NULL,
  experiments_json LONGTEXT NULL,
  capital DECIMAL(18,2) NOT NULL DEFAULT 100000,
  interval_minutes INT NOT NULL DEFAULT 5,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ai_lab_iteration_user_time (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
